In [4]:
import pandas as pd
import openpyxl
import os

In [5]:
path = "../src/data/tortilleria.xlsx"

df = pd.read_excel(path)

print(df.dtypes)

Nombre           str
SKU            int64
Precio       float64
Cantidad       int64
Categoria        str
dtype: object

In [6]:
row = df[df["Nombre"] == "Leche 1L"]

row

     Nombre            SKU  Precio  Cantidad Categoria
0  Leche 1L  7501031311309    25.5         2   Lácteos

In [7]:
rows_dict = row.to_dict(orient= "records")

print(rows_dict)

[{'Nombre': 'Leche 1L', 'SKU': 7501031311309, 'Precio': 25.5, 'Cantidad': 2, 'Categoria': 'Lácteos'}]

In [8]:
df.loc[df['Nombre'] == 'Leche 1L', "Nombre"] = 'Leche 500ml'

df

            Nombre            SKU  Precio  Cantidad  Categoria
0      Leche 500ml  7501031311309    25.5         2    Lácteos
1        Pan Bimbo  7501000123456    35.0         5  Panadería
2  Coca Cola 600ml  7501000654321    22.0        10    Bebidas

In [9]:
print('Update dataframe')
df.loc[df['Nombre'] == 'Leche 500ml', 'Cantidad'] = 4

df

            Nombre            SKU  Precio  Cantidad  Categoria
0      Leche 500ml  7501031311309    25.5         4    Lácteos
1        Pan Bimbo  7501000123456    35.0         5  Panadería
2  Coca Cola 600ml  7501000654321    22.0        10    Bebidas

In [10]:
#Drops a value in a table by a condition

df = df.drop(df[df["Nombre"] == "Pan Bimbo"].index) #Drops the index where Nombre is equal to Pan Bimbo

df

            Nombre            SKU  Precio  Cantidad Categoria
0      Leche 500ml  7501031311309    25.5         4   Lácteos
2  Coca Cola 600ml  7501000654321    22.0        10   Bebidas