In [1]:
import pandas as pd
import openpyxl
import os

In [2]:
path = "../src/data/tortilleria.xlsx"

df = pd.read_excel(path)

print(df.dtypes)

Nombre           str
SKU            int64
Precio       float64
Cantidad       int64
Categoria        str
dtype: object

In [3]:
row = df[df["Nombre"] == "Leche 1L"]
row

     Nombre            SKU  Precio  Cantidad Categoria
0  Leche 1L  7501031311309    25.5         2   Lácteos

In [4]:
rows_dict = row.to_dict(orient= "records")

print(rows_dict)

[{'Nombre': 'Leche 1L', 'SKU': 7501031311309, 'Precio': 25.5, 'Cantidad': 2, 'Categoria': 'Lácteos'}]

In [5]:
df.loc[df['Nombre'] == 'Leche 1L', "Nombre"] = 'Leche 500ml'

df

                  Nombre            SKU  Precio  Cantidad  Categoria
0            Leche 500ml  7501031311309    25.5         2    Lácteos
1        Coca Cola 600ml  7501000654321    22.0        10    Bebidas
2              Pan Bimbo  7501000123456    35.0         5  Panadería
3          Leche Lala 1L  7501000987654    28.5         8    Lácteos
4       Huevos 12 piezas  7501000112233    42.0        12  Abarrotes
5              Arroz 1kg  7501000445566    25.0        20     Granos
6           Frijoles 1kg  7501000778899    30.0        15     Granos
7  Sabritas Original 45g  7501000123987    18.0        25    Botanas
8     Agua Bonafont 1.5L  7501000654789    15.0        30    Bebidas
9             Jabón Zote  7501000321654    12.0        18   Limpieza

In [6]:
print('Update dataframe')
df.loc[df['Nombre'] == 'Leche 500ml', 'Cantidad'] = 4

df

Update dataframe

                  Nombre            SKU  Precio  Cantidad  Categoria
0            Leche 500ml  7501031311309    25.5         4    Lácteos
1        Coca Cola 600ml  7501000654321    22.0        10    Bebidas
2              Pan Bimbo  7501000123456    35.0         5  Panadería
3          Leche Lala 1L  7501000987654    28.5         8    Lácteos
4       Huevos 12 piezas  7501000112233    42.0        12  Abarrotes
5              Arroz 1kg  7501000445566    25.0        20     Granos
6           Frijoles 1kg  7501000778899    30.0        15     Granos
7  Sabritas Original 45g  7501000123987    18.0        25    Botanas
8     Agua Bonafont 1.5L  7501000654789    15.0        30    Bebidas
9             Jabón Zote  7501000321654    12.0        18   Limpieza

In [7]:
#Drops a value in a table by a condition

df = df.drop(df[df["Nombre"] == "Pan Bimbo"].index) #Drops the index where Nombre is equal to Pan Bimbo

df

                  Nombre            SKU  Precio  Cantidad  Categoria
0            Leche 500ml  7501031311309    25.5         4    Lácteos
1        Coca Cola 600ml  7501000654321    22.0        10    Bebidas
3          Leche Lala 1L  7501000987654    28.5         8    Lácteos
4       Huevos 12 piezas  7501000112233    42.0        12  Abarrotes
5              Arroz 1kg  7501000445566    25.0        20     Granos
6           Frijoles 1kg  7501000778899    30.0        15     Granos
7  Sabritas Original 45g  7501000123987    18.0        25    Botanas
8     Agua Bonafont 1.5L  7501000654789    15.0        30    Bebidas
9             Jabón Zote  7501000321654    12.0        18   Limpieza

In [12]:
search_row = df[df["SKU"] == 7501000112233]

search_row

             Nombre            SKU  Precio  Cantidad  Categoria
4  Huevos 12 piezas  7501000112233    42.0        12  Abarrotes