In [11]:
import pandas as pd
import openpyxl
import os

In [30]:
path = "../src/data/tortilleria.xlsx"

df = pd.read_excel(path)

print(df.dtypes)

Nombre           str
SKU            int64
Precio       float64
Cantidad       int64
Categoria        str
dtype: object

In [31]:
row = df[df["Nombre"] == "Leche 1L"]

row

     Nombre            SKU  Precio  Cantidad Categoria
0  Leche 1L  7501031311309    25.5         2   Lácteos

In [32]:
rows_dict = row.to_dict(orient= "records")

print(rows_dict)

[{'Nombre': 'Leche 1L', 'SKU': 7501031311309, 'Precio': 25.5, 'Cantidad': 2, 'Categoria': 'Lácteos'}]

In [33]:
df.loc[df['Nombre'] == 'Leche 1L', "Nombre"] = 'Leche 500ml'

df

        Nombre            SKU  Precio  Cantidad Categoria
0  Leche 500ml  7501031311309    25.5         2   Lácteos

In [34]:
df.loc[df['Nombre'] == 'Leche 500ml', 'Cantidad'] = 4

df

        Nombre            SKU  Precio  Cantidad Categoria
0  Leche 500ml  7501031311309    25.5         4   Lácteos